path: D:\BragBoard-main\Face Detection
train:
- D:\BragBoard-main\Face Detection\Face Dataset\WIDER_train\WIDER_train\images
- D:\BragBoard-main\Face Detection\Hand Gesture
val:
- D:\BragBoard-main\Face Detection\Face Dataset\WIDER_val\WIDER_val\images
- D:\BragBoard-main\Face Detection\Hand Gesture
names:
  0: face
  1: call
  2: dislike
  3: fist
  4: four
  5: like
  6: mute
  7: ok
  8: one
  9: palm
  10: peace
  11: peace_inverted
  12: rock
  13: stop
  14: three
  15: three2
  16: two_up
  17: two_up_inverted
  18: no_gesture
